var WORDS = [
  {id:1, ko:"안녕하세요", vi:"Hello", type:"danh từ"},
  {id:2, ko:"감사합니다", vi:"Thank you", type:"danh từ"},
  {id:3, ko:"사랑", vi:"Love", type:"danh từ"},
  {id:4, ko:"행복", vi:"Happy", type:"danh từ"},
  {id:5, ko:"친구", vi:"Friend", type:"danh từ"},
  {id:6, ko:"먹다", vi:"Eat", type:"động từ"},
  {id:7, ko:"마시다", vi:"Drink", type:"động từ"},
  {id:8, ko:"좋다", vi:"Good", type:"tính từ"},
  {id:9, ko:"나쁘다", vi:"Bad", type:"tính từ"},
  {id:10, ko:"학교", vi:"School", type:"danh từ"},
  {id:11, ko:"공부하다", vi:"Học", type:"động từ"},
  {id:12, ko:"책", vi:"Book", type:"danh từ"},
  {id:13, ko:"읽다", vi:"Read", type:"động từ"},
  {id:14, ko:"쓰기", vi:"Write", type:"động từ"},
  {id:15, ko:"예쁘다", vi:"Đẹp", type:"tính từ"},
  {id:16, ko:"날씨", vi:"Weather", type:"danh từ"},
  {id:17, ko:"춥다", vi:"Cold", type:"tính từ"},
  {id:18, ko:"덥다", vi:"Hot", type:"tính từ"},
  {id:19, ko:"보다", vi:"See", type:"động từ"},
  {id:20, ko:"듣다", vi:"Listen", type:"động từ"},
  {id:21, ko:"노래하다", vi:"Sing", type:"động từ"},
  {id:22, ko:"춤추다", vi:"Nhảy", type:"động từ"},
  {id:23, ko:"영화", vi:"Movie", type:"danh từ"},
  {id:24, ko:"음악", vi:"Music", type:"danh từ"},
  {id:25, ko:"운동하다", vi:"Tập thể thao", type:"động từ"},
  {id:26, ko:"달리다", vi:"To run", type:"động từ"},
  {id:27, ko:"걷다", vi:"Đi bộ", type:"động từ"},
  {id:28, ko:"행복하다", vi:"Hạnh phúc", type:"tính từ"},
  {id:29, ko:"슬프다", vi:"Buồn", type:"tính từ"},
  {id:30, ko:"친절하다", vi:"Tử tế", type:"tính từ"},
  {id:31, ko:"화나다", vi:"Tức giận", type:"tính từ"},
  {id:32, ko:"미소", vi:"Nụ cười", type:"danh từ"},
  {id:33, ko:"꿈", vi:"Giấc mơ", type:"danh từ"},
  {id:34, ko:"일하다", vi:"Làm việc", type:"động từ"},
  {id:35, ko:"쉬다", vi:"Nghỉ ngơi", type:"động từ"},
  {id:36, ko:"놀다", vi:"Chơi", type:"động từ"},
  {id:37, ko:"요리하다", vi:"Nấu ăn", type:"động từ"},
  {id:38, ko:"사다", vi:"Mua", type:"động từ"},
  {id:39, ko:"팔다", vi:"Bán", type:"động từ"},
  {id:40, ko:"걱정하다", vi:"Lo lắng", type:"động từ"},
  {id:41, ko:"아프다", vi:"Đau", type:"tính từ"},
  {id:42, ko:"건강하다", vi:"Khoẻ mạnh", type:"tính từ"},
  {id:43, ko:"바쁘다", vi:"Bận rộn", type:"tính từ"},
  {id:44, ko:"무료하다", vi:"Chán", type:"tính từ"},
  {id:45, ko:"영어", vi:"Tiếng Anh", type:"danh từ"},
  {id:46, ko:"한국어", vi:"Tiếng Hàn", type:"danh từ"},
  {id:47, ko:"베트남어", vi:"Tiếng Việt", type:"danh từ"},
  {id:48, ko:"말하다", vi:"Nói", type:"động từ"},
  {id:49, ko:"대화하다", vi:"Đàm thoại", type:"động từ"},
  {id:50, ko:"사람", vi:"Person", type:"danh từ"},
  {id:51, ko:"아이", vi:"Trẻ em", type:"danh từ"},
  {id:52, ko:"남자", vi:"Nam", type:"danh từ"},
  {id:53, ko:"여자", vi:"Nữ", type:"danh từ"},
  {id:54, ko:"청년", vi:"Thanh niên", type:"danh từ"},
  {id:55, ko:"노인", vi:"Người già", type:"danh từ"},
  {id:56, ko:"사랑하다", vi:"Yêu", type:"động từ"},
  {id:57, ko:"싫어하다", vi:"Ghét", type:"động từ"},
  {id:58, ko:"기쁘다", vi:"Vui mừng", type:"tính từ"},
  {id:59, ko:"슬프다", vi:"Buồn", type:"tính từ"},
  {id:60, ko:"행복하다", vi:"Hạnh phúc", type:"tính từ"},
  {id:61, ko:"화나다", vi:"Tức giận", type:"tính từ"},
  {id:62, ko:"웃다", vi:"Cười", type:"động từ"},
  {id:63, ko:"울다", vi:"Khóc", type:"động từ"},
  {id:64, ko:"걷다", vi:"Đi bộ", type:"động từ"},
  {id:65, ko:"달리다", vi:"Chạy", type:"động từ"},
  {id:66, ko:"자다", vi:"Ngủ", type:"động từ"},
  {id:67, ko:"일어나다", vi:"Thức dậy", type:"động từ"},
  {id:68, ko:"청소하다", vi:"Dọn dẹp", type:"động từ"},
  {id:69, ko:"씻다", vi:"Rửa", type:"động từ"},
  {id:70, ko:"요리하다", vi:"Nấu ăn", type:"động từ"},
  {id:71, ko:"먹다", vi:"Ăn", type:"động từ"},
  {id:72, ko:"마시다", vi:"Uống", type:"động từ"},
  {id:73, ko:"좋다", vi:"Tốt", type:"tính từ"},
  {id:74, ko:"나쁘다", vi:"Xấu", type:"tính từ"},
  {id:75, ko:"작다", vi:"Nhỏ", type:"tính từ"},
  {id:76, ko:"크다", vi:"Lớn", type:"tính từ"},
  {id:77, ko:"길다", vi:"Dài", type:"tính từ"},
  {id:78, ko:"짧다", vi:"Ngắn", type:"tính từ"},
  {id:79, ko:"빠르다", vi:"Quick", type:"tính từ"},
  {id:80, ko:"느리다", vi:"Chậm", type:"tính từ"},
  {id:81, ko:"덥다", vi:"Hot", type:"tính từ"},
  {id:82, ko:"춥다", vi:"Cold", type:"tính từ"},
  {id:83, ko:"편하다", vi:"Thoải mái", type:"tính từ"},
  {id:84, ko:"불편하다", vi:"Bất tiện", type:"tính từ"},
  {id:85, ko:"즐겁다", vi:"Vui", type:"tính từ"},
  {id:86, ko:"심심하다", vi:"Buồn chán", type:"tính từ"},
  {id:87, ko:"바쁘다", vi:"Bận", type:"tính từ"},
  {id:88, ko:"쉽다", vi:"Dễ", type:"tính từ"},
  {id:89, ko:"어렵다", vi:"Khó", type:"tính từ"},
  {id:90, ko:"재미있다", vi:"Thú vị", type:"tính từ"},
  {id:91, ko:"재미없다", vi:"Không thú vị", type:"tính từ"},
  {id:92, ko:"돈", vi:"Money", type:"danh từ"},
  {id:93, ko:"시간", vi:"Time", type:"danh từ"},
  {id:94, ko:"장소", vi:"Place", type:"danh từ"},
  {id:95, ko:"거리", vi:"Đường phố", type:"danh từ"},
  {id:96, ko:"나라", vi:"Nation", type:"danh từ"},
  {id:97, ko:"도시", vi:"Thành phố", type:"danh từ"},
  {id:98, ko:"마을", vi:"Làng", type:"danh từ"},
  {id:99, ko:"집", vi:"Home", type:"danh từ"},
  {id:100, ko:"방", vi:"Phòng", type:"danh từ"},
  {id:101, ko:"여우", vi:"Fox",
  {id:102, ko:"여자", vi:"Woman",
  {id:103, ko:"혀", vi:"Tongue",
  {id:104, ko:"아버지", vi:"Father",
  {id:105, ko:"소", vi:"Cow",
  {id:106, ko:"시계", vi:"Watch",
  {id:107, ko:"얘기", vi:"Story",
  {id:108, ko:"비누", vi:"Soap",
  {id:109, ko:"다리", vi:"Leg, Bridge", 
  {id:110, ko:"게", vi:"Crab",
  {id:111, ko:"개", vi:"Dog",
  {id:112, ko:"오빠", vi:"Elder Brother",
  {id:113, ko:"사", vi:"Number 4",
  {id:114, ko:"어디", vi:"Where",
  {id:115, ko:"구", vi:"Number 9"
];
