var WORDS = [
  {id:1, ko:"안녕하세요", vi:"Hello"},
  {id:2, ko:"감사합니다", vi:"Thank you"},
  {id:3, ko:"사랑", vi:"Love"},
  {id:4, ko:"행복", vi:"Happy"},
  {id:5, ko:"친구", vi:"Friend"},
  {id:6, ko:"먹다", vi:"Eat"},
  {id:7, ko:"마시다", vi:"Drink"},
  {id:8, ko:"좋다", vi:"Good"},
  {id:9, ko:"나쁘다", vi:"Bad"},
  {id:10, ko:"학교", vi:"School"},
  {id:11, ko:"공부하다", vi:"Study"},
  {id:12, ko:"책", vi:"Book"},
  {id:13, ko:"읽다", vi:"Read"},
  {id:14, ko:"쓰기", vi:"Write"},
  {id:15, ko:"예쁘다", vi:"Pretty"},
  {id:16, ko:"날씨", vi:"Weather"},
  {id:17, ko:"춥다", vi:"Cold"},
  {id:18, ko:"덥다", vi:"Hot"},
  {id:19, ko:"보다", vi:"See"},
  {id:20, ko:"듣다", vi:"Listen"},
  {id:21, ko:"노래하다", vi:"Sing"},
  {id:22, ko:"춤추다", vi:"Dance"},
  {id:23, ko:"영화", vi:"Movie"},
  {id:24, ko:"음악", vi:"Music"},
  {id:25, ko:"운동하다", vi:"Exercise"},
  {id:26, ko:"달리다", vi:"Run"},
  {id:27, ko:"걷다", vi:"Walk"},
  {id:28, ko:"행복하다", vi:"Happy"},
  {id:29, ko:"슬프다", vi:"Sad"},
  {id:30, ko:"친절하다", vi:"Kind"},
  {id:31, ko:"화나다", vi:"Angry"},
  {id:32, ko:"미소", vi:"Smile"},
  {id:33, ko:"꿈", vi:"Dream"},
  {id:34, ko:"일하다", vi:"Work"},
  {id:35, ko:"쉬다", vi:"Rest"},
  {id:36, ko:"놀다", vi:"Play"},
  {id:37, ko:"요리하다", vi:"Cook"},
  {id:38, ko:"사다", vi:"Buy"},
  {id:39, ko:"팔다", vi:"Sell"},
  {id:40, ko:"걱정하다", vi:"Worry"},
  {id:41, ko:"아프다", vi:"Sick"},
  {id:42, ko:"건강하다", vi:"Healthy"},
  {id:43, ko:"바쁘다", vi:"Busy"},
  {id:44, ko:"무료하다", vi:"Bored"},
  {id:45, ko:"영어", vi:"English"},
  {id:46, ko:"한국어", vi:"Korean"},
  {id:47, ko:"베트남어", vi:"Vietnamese"},
  {id:48, ko:"말하다", vi:"Speak"},
  {id:49, ko:"대화하다", vi:"Talk"},
  {id:50, ko:"사람", vi:"Person"},
  {id:51, ko:"아이", vi:"Child"},
  {id:52, ko:"남자", vi:"Male"},
  {id:53, ko:"여자", vi:"Female"},
  {id:54, ko:"청년", vi:"Youth"},
  {id:55, ko:"노인", vi:"Elder"},
  {id:56, ko:"사랑하다", vi:"Love"},
  {id:57, ko:"싫어하다", vi:"Hate"},
  {id:58, ko:"기쁘다", vi:"Glad"},
  {id:59, ko:"웃다", vi:"Laugh"},
  {id:60, ko:"울다", vi:"Cry"},
  {id:61, ko:"자다", vi:"Sleep"},
  {id:62, ko:"일어나다", vi:"Wake up"},
  {id:63, ko:"청소하다", vi:"Clean"},
  {id:64, ko:"씻다", vi:"Wash"},
  {id:65, ko:"작다", vi:"Small"},
  {id:66, ko:"크다", vi:"Big"},
  {id:67, ko:"길다", vi:"Long"},
  {id:68, ko:"짧다", vi:"Short"},
  {id:69, ko:"빠르다", vi:"Fast"},
  {id:70, ko:"느리다", vi:"Slow"},
  {id:71, ko:"편하다", vi:"Comfortable"},
  {id:72, ko:"불편하다", vi:"Uncomfortable"},
  {id:73, ko:"즐겁다", vi:"Joyful"},
  {id:74, ko:"심심하다", vi:"Bored"},
  {id:75, ko:"쉽다", vi:"Easy"},
  {id:76, ko:"어렵다", vi:"Difficult"},
  {id:77, ko:"재미있다", vi:"Interesting"},
  {id:78, ko:"재미없다", vi:"Boring"},
  {id:79, ko:"돈", vi:"Money"},
  {id:80, ko:"시간", vi:"Time"},
  {id:81, ko:"장소", vi:"Place"},
  {id:82, ko:"거리", vi:"Street"},
  {id:83, ko:"나라", vi:"Nation"},
  {id:84, ko:"도시", vi:"City"},
  {id:85, ko:"마을", vi:"Village"},
  {id:86, ko:"집", vi:"Home"},
  {id:87, ko:"방", vi:"Room"},
  {id:88, ko:"구", vi:"District"},
  {id:89, ko:"어디", vi:"Where"},
  {id:90, ko:"사", vi:"Company / Person"},
  {id:91, ko:"오빠", vi:"Older brother"},
  {id:92, ko:"개", vi:"Dog"},
  {id:93, ko:"게", vi:"Crab"},
  {id:94, ko:"여우", vi:"Fox"},
  {id:95, ko:"여자", vi:"Woman"},
  {id:96, ko:"아버지", vi:"Father"},
  {id:97, ko:"혀", vi:"Tongue"},
  {id:98, ko:"다리", vi:"Leg / Bridge"},
  {id:99, ko:"비누", vi:"Soap"},
  {id:100, ko:"ㅒ기", vi:"Example"},
  {id:101, ko:"시계", vi:"Clock"},
  {id:102, ko:"소", vi:"Cow"},
  {id:103, ko:"뽀뽀", vi:"Kiss"},
  {id:104, ko:"고래", vi:"Whale"},
  {id:105, ko:"구두", vi:"Shoes"},
  {id:106, ko:"너", vi:"You"},
  {id:107, ko:"포도", vi:"Grape"},
  {id:108, ko:"파", vi:"Green onion / Leek"},
  {id:109, ko:"왜", vi:"Why"},
  {id:110, ko:"돼지", vi:"Pig"},
  {id:111, ko:"카드", vi:"Card"},
  {id:112, ko:"코", vi:"Nose"},
  {id:113, ko:"고기", vi:"Meat"},
  {id:114, ko:"가구", vi:"Furniture"},
  {id:115, ko:"오이", vi:"Cucumber"},
  {id:116, ko:"아이", vi:"Child"},
  {id:117, ko:"누나", vi:"Older sister"},
  {id:118, ko:"카메라", vi:"Camera"},
  {id:119, ko:"거미", vi:"Spider"},
  {id:120, ko:"파리", vi:"Fly"},
  {id:121, ko:"빵", vi:"Bread"},
  {id:122, ko:"밥", vi:"Rice"},
  {id:123, ko:"귀", vi:"Ear"},
  {id:124, ko:"캐다", vi:"Dig"},
  {id:125, ko:"타다", vi:"Ride / Burn"},
  {id:126, ko:"코트", vi:"Coat"},
  {id:127, ko:"하마", vi:"Hippopotamus"},
  {id:128, ko:"사과", vi:"Apple"},
  {id:129, ko:"허리", vi:"Waist"},
  {id:130, ko:"버스", vi:"Bus"},
  {id:131, ko:"주스", vi:"Juice"},
  {id:132, ko:"베개", vi:"Pillow"},
  {id:133, ko:"깨다", vi:"Wake up / Break"},
  {id:134, ko:"뜨다", vi:"Float / Open eyes"},
  {id:135, ko:"회사", vi:"Company"},
  {id:136, ko:"조개", vi:"Clam"},
  {id:137, ko:"노래", vi:"Song"},
  {id:138, ko:"의사", vi:"Doctor"},
  {id:139, ko:"묘기", vi:"Trick"},
  {id:140, ko:"싸다", vi:"Cheap / Pack"},
  {id:141, ko:"교류", vi:"Exchange"},
  {id:142, ko:"가위", vi:"Scissors"},
  {id:143, ko:"뿌리", vi:"Root"},
  {id:144, ko:"화가", vi:"Painter / Angry"},
  {id:145, ko:"짜다", vi:"Salty"},
  {id:146, ko:"가짜", vi:"Fake"},
  {id:147, ko:"교회", vi:"Church"},
  {id:148, ko:"커피", vi:"Coffee"},
  {id:149, ko:"꼬리", vi:"Tail"},
  {id:150, ko:"포크", vi:"Fork"},
  {id:151, ko:"겨자", vi:"Mustard"},
  {id:152, ko:"까치", vi:"Magpie"},
  {id:153, ko:"아빠", vi:"Dad"},
  {id:154, ko:"의자", vi:"Chair"},
  {id:155, ko:"치마", vi:"Skirt"},
  {id:156, ko:"차다", vi:"Kick / Wear (watch)"},
  {id:157, ko:"차", vi:"Car / Tea"},
  {id:158, ko:"기차", vi:"Train"},
  {id:159, ko:"개다", vi:"Clear up (weather)"},
  {id:160, ko:"따다", vi:"Pick / Pluck"},
  {id:161, ko:"띠", vi:"Belt / Stripe"},
  {id:162, ko:"뛰다", vi:"Run / Jump"},
  {id:163, ko:"쓰다", vi:"Write / Use"},
  {id:164, ko:"아우", vi:"Younger sibling (male)"},
  {id:165, ko:"별", vi:"Star"},
  {id:166, ko:"가을", vi:"Autumn"},
  {id:167, ko:"월요일", vi:"Monday"},
  {id:168, ko:"향수", vi:"Perfume"},
  {id:169, ko:"형", vi:"Older brother (male)"},
  {id:170, ko:"엄마", vi:"Mom"},
  {id:171, ko:"달걀", vi:"Egg"},
  {id:172, ko:"계란", vi:"Egg"},
  {id:173, ko:"귤", vi:"Tangerine"},
  {id:174, ko:"열다", vi:"Open"},
  {id:175, ko:"경찰", vi:"Police"},
  {id:176, ko:"겨울", vi:"Winter"},
  {id:177, ko:"이", vi:"Tooth / This"},
  {id:178, ko:"위", vi:"Above / Stomach"},
  {id:179, ko:"라디오", vi:"Radio"},
  {id:180, ko:"달력", vi:"Calendar"},
  {id:181, ko:"화장실", vi:"Bathroom"},
  {id:182, ko:"딸기", vi:"Strawberry"},
  {id:183, ko:"칠판", vi:"Blackboard"},
  {id:184, ko:"교실", vi:"Classroom"},
  {id:185, ko:"거울", vi:"Mirror"},
  {id:186, ko:"병원", vi:"Hospital"},
  {id:187, ko:"가방", vi:"Bag"},
  {id:188, ko:"무릎", vi:"Knee"},
  {id:189, ko:"커피숍", vi:"Coffee shop"},
  {id:190, ko:"컵", vi:"Cup"},
  {id:191, ko:"앞", vi:"Front"},
  {id:192, ko:"꽃", vi:"Flower"},
  {id:193, ko:"낮", vi:"Daytime"},
  {id:194, ko:"오", vi:"Oh / Five"},
  {id:195, ko:"젓가락", vi:"Chopsticks"},
  {id:196, ko:"끝", vi:"End"},
  {id:197, ko:"옷", vi:"Clothes"},
  {id:198, ko:"솥", vi:"Pot"},
  {id:199, ko:"닫다", vi:"Close"},
  {id:200, ko:"숟가락", vi:"Spoon"},
  {id:201, ko:"손", vi:"Hand"},
  {id:202, ko:"담배", vi:"Cigarette"},
  {id:203, ko:"해", vi:"Sun"},
  {id:204, ko:"칫솔", vi:"Toothbrush"},
  {id:205, ko:"휴지", vi:"Tissue, Toilet paper"},
  {id:206, ko:"이불", vi:"Blanket"},
  {id:207, ko:"신발", vi:"Shoes"},
  {id:208, ko:"눈", vi:"Eye / Snow"},
  {id:209, ko:"한국", vi:"Korea"},
  {id:210, ko:"녹차", vi:"Green tea"},
  {id:211, ko:"밖", vi:"Outside"},
  {id:212, ko:"부엌", vi:"Kitchen"},
  {id:213, ko:"유리", vi:"Glass"},
  {id:214, ko:"야구", vi:"Baseball"},
  {id:215, ko:"우유", vi:"Milk"}
];
